setxkbmap "us,ru" -option grp:alt_shift_toggle
xmodmap ~/.Xmodmap

configure-monitors
xrdb -merge ~/.Xresources
picom -b
colwarm
xwallpaper --maximize ~/.config/wall.png
unclutter &

sxhkd &
slstatus &
dunst &
check-battery-loop &

dnetwork first

exec dwm
