setxkbmap "us,ru" -option grp:alt_shift_toggle
xmodmap ~/.Xmodmap

configure-monitors
xrdb -merge ~/.Xresources
picom -b
colwarm
xwallpaper --center ~/.config/wall.png
unclutter &

sxhkd &
slstatus &
dunst &
check-battery &

wifi TP-Link_8A42

exec dwm
