export DOTFILES=$HOME/dt
export PATH=$PATH:$DOTFILES/scripts:$DOTFILES/scripts/personal

export EDITOR=nvim
export TERMINAL=st
export BROWSER=chromium
export OPENER=open

export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.local/cache

if [ "$(tty)" = "/dev/tty1" ]; then
    exec startx
fi

