export ZSH="$HOME/.oh-my-zsh"

# prompt customization
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '
setopt PROMPT_SUBST
NEWLINE=$'\n'
PROMPT='%F{yellow}%(1j.jobs: %j .)%f%F{blue}%~%f %F{red}${vcs_info_msg_0_}%f${NEWLINE}$ '

plugins=(
  git
  asdf
#  fzf-zsh-plugin
  zsh-syntax-highlighting
#  vi-mode
#  laravel-sail
#  docker
#  docker-compose
#  kubectl
)

source $ZSH/oh-my-zsh.sh

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.local/state/zsh/history

setopt notify
unsetopt beep
bindkey -v

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
bindkey -s "^[v" "fzf-open^M"

alias lf=lfub

source "$DOTFILES/config/zsh/aliases"

