#!/bin/bash

# WIP

LAPTOP_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-2"

# ext_connected=false
# [ "$(xrandr | grep ' connected' | grep \"$1\")" != "" ] && ext_connected=true
#
# echo $ext_connected

# check_connected() {
#     echo "$(xrandr | grep " connected" | grep "$1")"
# }



xrandr --output "$LAPTOP_MONITOR" --auto --mode 1920x1080
xrandr --output "$EXTERNAL_MONITOR" --auto --mode 1920x1080 \
    --same-as eDP-1

