#!/bin/bash

LAPTOP_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-2"

xrandr --output "$LAPTOP_MONITOR" --auto --mode 1920x1080
xrandr --output "$EXTERNAL_MONITOR" --auto --mode 1920x1080 \
    --same-as eDP-1

