#!/bin/sh

# WIP

case "$1" in
    toggle-mute) amixer sset Master toggle ;;
    up) amixer sset Master 10%+ ;;
    down) amixer sset Master 10%- ;;
    toggle-pause) mpc toggle ;;
    next) mpc next ;;
    prev) mpc prev ;;
esac

