#!/bin/sh

f="$1"
mime=$(readlink -f "$f" | xargs -I {} file --mime-type -b "{}")
case $mime in
	image/*) setsid -f sxiv "$f" >/dev/null 2>&1 ;;
    text/*) $EDITOR "$f";;
	audio/*|video/x-ms-asf) mpv --audio-display=no "$f" ;;
	video/*) setsid -f mpv "$f" -quiet >/dev/null 2>&1 ;;
	application/pdf) setsid -f zathura "$f" ;;
	application/x-bittorrent) open-torrent "$f" ;;
    *) $EDITOR "$f";;
esac

